sequenceDiagram
    User->>RDS: Request
    RDS->>S3: Request
    S3->>KMS: Request
    KMS->>SM: Request
    SM-->>KMS: Response
    KMS-->>S3: Response
    S3-->>RDS: Response
    RDS-->>User: Response